define michael = Character("Michael", color="#00ccff")
define patty = Character("Patty", color="#ff66cc")
define robot = Character("Wellness Robot", color="#FF0000")
define officer1 = Character("LEAD OFFICER - Type: Human")
define officer2 = Character("SECOND OFFICER - Type: Clone")
define officer3 = Character("THIRD OFFICER - Type: Human")
define judge = Character("AI JUDGE", color="#FFFFFF")
define player = DynamicCharacter("player_name")
define commander = Character("Commander One-Eye", color="#CBC3E3")
define sr = Character("Robot Sergeant")
define rizzo = Character("Rizzo", color = "#FFA500")
define uuna = Character("Uuna", color = "#5F9EA0")
define f8lure = Character("F8Lure", color = "#00A36C")
define milo = Character("Milo", color = "#00A36C")

define robot2 = Character("Voice Coming From The Speakers", color="#058c05")